#!/bin/bash


# Will be executed as user "root".

# Name this file "daemon" in your plugin-archive. It will be renamed to NAME
# during installation

if [ -x /usr/bin/logger ]
then
    /usr/bin/logger "This is just a sample DAEMON script from Sample Plugin"
fi

. $LBHOMEDIR/libs/bashlib/notify.sh


$LBHOMEDIR/bin/plugins/io/inoutpinconfig.pl
$LBHOMEDIR/bin/plugins/io/handleinputs.pl 


exit 0
