#!/bin/bash


# Will be executed as user "root".

PLUGINNAME=REPLACELBPPLUGINDIR
PATH="/sbin:/bin:/usr/sbin:/usr/bin:$LBHOMEDIR/bin:$LBHOMEDIR/sbin"

ENVIRONMENT=$(cat /etc/environment)
export $ENVIRONMENT

$LBHOMEDIR/bin/plugins/${PLUGINNAME}/wrapper.sh start


exit 0
